"""add clarification model

Revision ID: 440281f2085a
Revises: e357274b7390
Create Date: 2026-02-07 15:16:19.397386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440281f2085a'
down_revision = 'e357274b7390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clarification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clarification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_created_at'))

    op.drop_table('clarification')
    # ### end Alembic commands ###
