"""add is_admin to user

Revision ID: 51260d562399
Revises: 393e2a2e10b2
Create Date: 2026-02-07 11:12:48.507261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51260d562399'
down_revision = '393e2a2e10b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
