"""add is_public to decision

Revision ID: 56c03d72fd21
Revises: b6b3f100b4d3
Create Date: 2026-02-07 15:07:56.165607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c03d72fd21'
down_revision = 'b6b3f100b4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
