"""remove criteria and scores

Revision ID: bf05b1f250c1
Revises: 4d2fc4752ede
Create Date: 2026-02-08 11:23:38.391910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf05b1f250c1'
down_revision = '4d2fc4752ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criterion')
    op.drop_table('score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('option_id', sa.INTEGER(), nullable=True),
    sa.Column('criterion_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('decision_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
