"""Add UserAction model

Revision ID: d78f169e3e9b
Revises: 440281f2085a
Create Date: 2026-02-07 21:25:10.957909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78f169e3e9b'
down_revision = '440281f2085a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_action_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_action_timestamp'))

    op.drop_table('user_action')
    # ### end Alembic commands ###
