"""Add category to decision

Revision ID: fcd864c75d0e
Revises: d78f169e3e9b
Create Date: 2026-02-07 21:26:43.708202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd864c75d0e'
down_revision = 'd78f169e3e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
